name: Deploy
on:
  push:
    brnaches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into DigitalOcean and run deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/salmonella
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S ./deploy.sh